// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package v2authdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addRole = `-- name: AddRole :exec
INSERT INTO v2.user_roles(user_id, role) VALUES ($1, $2)
`

type AddRoleParams struct {
	UserID uuid.UUID
	Role   string
}

func (q *Queries) AddRole(ctx context.Context, arg AddRoleParams) error {
	_, err := q.db.Exec(ctx, addRole, arg.UserID, arg.Role)
	return err
}

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(*) FROM v2.users u JOIN v2.user_roles r ON r.user_id = u.id WHERE u.active AND r.role = 'admin'
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthAudit = `-- name: CreateAuthAudit :exec
INSERT INTO v2.auth_audit(id, actor_id, target_id, action, details) VALUES ($1, $2, $3, $4, $5)
`

type CreateAuthAuditParams struct {
	ID       uuid.UUID
	ActorID  *uuid.UUID
	TargetID *uuid.UUID
	Action   string
	Details  []byte
}

func (q *Queries) CreateAuthAudit(ctx context.Context, arg CreateAuthAuditParams) error {
	_, err := q.db.Exec(ctx, createAuthAudit,
		arg.ID,
		arg.ActorID,
		arg.TargetID,
		arg.Action,
		arg.Details,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO v2.sessions(token_hash, user_id, csrf_token, expires_at) VALUES ($1, $2, $3, $4)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	CsrfToken string
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.CsrfToken,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO v2.users(id, username, password_hash, active) VALUES ($1, $2, $3, true)
`

type CreateUserParams struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.ID, arg.Username, arg.PasswordHash)
	return err
}

const deleteRoles = `-- name: DeleteRoles :exec
DELETE FROM v2.user_roles WHERE user_id = $1
`

func (q *Queries) DeleteRoles(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoles, userID)
	return err
}

const getAccountRequest = `-- name: GetAccountRequest :one
SELECT request_hash, password_hash, response FROM v2.account_requests WHERE actor_id = $1 AND operation = $2 AND key = $3
`

type GetAccountRequestParams struct {
	ActorID   uuid.UUID
	Operation string
	Key       uuid.UUID
}

type GetAccountRequestRow struct {
	RequestHash  []byte
	PasswordHash string
	Response     []byte
}

func (q *Queries) GetAccountRequest(ctx context.Context, arg GetAccountRequestParams) (GetAccountRequestRow, error) {
	row := q.db.QueryRow(ctx, getAccountRequest, arg.ActorID, arg.Operation, arg.Key)
	var i GetAccountRequestRow
	err := row.Scan(&i.RequestHash, &i.PasswordHash, &i.Response)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT s.token_hash, s.user_id, s.csrf_token, s.expires_at, u.username
FROM v2.sessions s JOIN v2.users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND NOT s.revoked AND s.expires_at > clock_timestamp() AND u.active
`

type GetSessionRow struct {
	TokenHash []byte
	UserID    uuid.UUID
	CsrfToken string
	ExpiresAt time.Time
	Username  string
}

func (q *Queries) GetSession(ctx context.Context, tokenHash []byte) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, tokenHash)
	var i GetSessionRow
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CsrfToken,
		&i.ExpiresAt,
		&i.Username,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, active FROM v2.users WHERE id = $1
`

type GetUserRow struct {
	ID       uuid.UUID
	Username string
	Active   bool
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(&i.ID, &i.Username, &i.Active)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, active FROM v2.users WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	Active       bool
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Active,
	)
	return i, err
}

const listAuthAudit = `-- name: ListAuthAudit :many
SELECT id, actor_id, target_id, action, details, created_at FROM v2.auth_audit ORDER BY created_at DESC, id DESC LIMIT 500
`

func (q *Queries) ListAuthAudit(ctx context.Context) ([]V2AuthAudit, error) {
	rows, err := q.db.Query(ctx, listAuthAudit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []V2AuthAudit{}
	for rows.Next() {
		var i V2AuthAudit
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.TargetID,
			&i.Action,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT role FROM v2.user_roles WHERE user_id = $1 ORDER BY role
`

func (q *Queries) ListRoles(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, active FROM v2.users ORDER BY username
`

type ListUsersRow struct {
	ID       uuid.UUID
	Username string
	Active   bool
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.ID, &i.Username, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccountAdministration = `-- name: LockAccountAdministration :exec
SELECT pg_advisory_xact_lock(224027, 1)
`

func (q *Queries) LockAccountAdministration(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockAccountAdministration)
	return err
}

const lockUser = `-- name: LockUser :one
SELECT id, username, password_hash, active FROM v2.users WHERE id = $1 FOR UPDATE
`

type LockUserRow struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	Active       bool
}

func (q *Queries) LockUser(ctx context.Context, id uuid.UUID) (LockUserRow, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	var i LockUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Active,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE v2.sessions SET revoked = true WHERE token_hash = $1
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, tokenHash)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE v2.sessions SET revoked = true WHERE user_id = $1 AND NOT revoked
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const saveAccountRequest = `-- name: SaveAccountRequest :exec
INSERT INTO v2.account_requests(actor_id, operation, key, request_hash, password_hash, response) VALUES ($1, $2, $3, $4, $5, $6)
`

type SaveAccountRequestParams struct {
	ActorID      uuid.UUID
	Operation    string
	Key          uuid.UUID
	RequestHash  []byte
	PasswordHash string
	Response     []byte
}

func (q *Queries) SaveAccountRequest(ctx context.Context, arg SaveAccountRequestParams) error {
	_, err := q.db.Exec(ctx, saveAccountRequest,
		arg.ActorID,
		arg.Operation,
		arg.Key,
		arg.RequestHash,
		arg.PasswordHash,
		arg.Response,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE v2.users SET active = $2, password_hash = CASE WHEN $3::text = '' THEN password_hash ELSE $3::text END WHERE id = $1
`

type UpdateUserParams struct {
	ID           uuid.UUID
	Active       bool
	PasswordHash string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser, arg.ID, arg.Active, arg.PasswordHash)
	return err
}
