// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: factory.sql

package v2db

import (
	"context"
)

const v2SchemaVersion = `-- name: V2SchemaVersion :one
SELECT 2::bigint AS version
`

// v2 factory handlers use transaction-bound pgx queries for compound documents.
// This generated package is intentionally kept available for future query extraction.
func (q *Queries) V2SchemaVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, v2SchemaVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}
