// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package v2db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type V2AccountRequest struct {
	ActorID      uuid.UUID
	Operation    string
	Key          uuid.UUID
	RequestHash  []byte
	PasswordHash string
	Response     []byte
	CreatedAt    time.Time
}

type V2AuditEvent struct {
	ID         int64
	ActorID    uuid.UUID
	ActorRole  string
	Operation  string
	EntityID   uuid.UUID
	Reason     string
	Details    []byte
	RecordedAt time.Time
}

type V2AuthAudit struct {
	ID        uuid.UUID
	ActorID   *uuid.UUID
	TargetID  *uuid.UUID
	Action    string
	Details   []byte
	CreatedAt time.Time
}

type V2BomLine struct {
	RevisionID      uuid.UUID
	ComponentItemID uuid.UUID
	Quantity        int64
}

type V2BomRevision struct {
	ID             uuid.UUID
	FinishedItemID uuid.UUID
	Revision       string
	Status         string
	CreatedBy      uuid.UUID
	ApprovedBy     *uuid.UUID
	ApprovedAt     pgtype.Timestamptz
}

type V2BomRevisionView struct {
	ID             uuid.UUID
	FinishedItemID uuid.UUID
	Revision       string
	Status         string
	CreatedBy      uuid.UUID
	ApprovedBy     *uuid.UUID
	ApprovedAt     pgtype.Timestamptz
	Lines          interface{}
}

type V2CommandReplay struct {
	AccountID   uuid.UUID
	Operation   string
	RequestKey  uuid.UUID
	RequestHash string
	Response    []byte
	CreatedAt   time.Time
}

type V2DefectReason struct {
	ID     uuid.UUID
	Code   string
	Name   string
	Active bool
}

type V2Document struct {
	ID               uuid.UUID
	Kind             string
	OrderID          *uuid.UUID
	SourceDocumentID *uuid.UUID
	WorkSessionID    *uuid.UUID
	OutputLotID      *uuid.UUID
	OutputLotCode    string
	LocationID       *uuid.UUID
	Quantity         int64
	AcceptedQuantity int64
	RejectedQuantity int64
	DefectReasonID   *uuid.UUID
	Reason           string
	Disposition      string
	OccurredAt       time.Time
	Version          int64
	Status           string
	HasVariance      bool
	CreatedBy        uuid.UUID
	CreatedAt        time.Time
	PostedBy         *uuid.UUID
	PostedAt         pgtype.Timestamptz
}

type V2DocumentDependency struct {
	ParentID uuid.UUID
	ChildID  uuid.UUID
}

type V2DocumentLine struct {
	DocumentID uuid.UUID
	LineNumber int32
	LotID      uuid.UUID
	LocationID uuid.UUID
	Quantity   int64
}

type V2DocumentView struct {
	ID                        uuid.UUID
	Kind                      string
	OrderID                   *uuid.UUID
	SourceDocumentID          *uuid.UUID
	WorkSessionID             *uuid.UUID
	OutputLotID               *uuid.UUID
	OutputLotCode             string
	LocationID                *uuid.UUID
	Quantity                  int64
	AcceptedQuantity          int64
	RejectedQuantity          int64
	DefectReasonID            *uuid.UUID
	Reason                    string
	Disposition               string
	OccurredAt                time.Time
	Version                   int64
	Status                    string
	HasVariance               bool
	CreatedBy                 uuid.UUID
	CreatedAt                 time.Time
	PostedBy                  *uuid.UUID
	PostedAt                  pgtype.Timestamptz
	ReversalID                *uuid.UUID
	Lines                     interface{}
	InspectionResults         interface{}
	AvailablePendingQuantity  interface{}
	AvailableAcceptedQuantity interface{}
	AvailableRejectedQuantity interface{}
	AvailableReworkQuantity   interface{}
}

type V2InspectionItem struct {
	RevisionID uuid.UUID
	ItemCode   string
	Name       string
	Required   bool
	Acceptance string
}

type V2InspectionResult struct {
	DocumentID uuid.UUID
	ItemCode   string
	Result     string
	Note       string
}

type V2InspectionRevision struct {
	ID             uuid.UUID
	FinishedItemID uuid.UUID
	Revision       string
	Status         string
	CreatedBy      uuid.UUID
	ApprovedBy     *uuid.UUID
	ApprovedAt     pgtype.Timestamptz
}

type V2InspectionRevisionView struct {
	ID             uuid.UUID
	FinishedItemID uuid.UUID
	Revision       string
	Status         string
	CreatedBy      uuid.UUID
	ApprovedBy     *uuid.UUID
	ApprovedAt     pgtype.Timestamptz
	Items          interface{}
}

type V2InventoryBalance struct {
	ItemID     uuid.UUID
	LotID      uuid.UUID
	LocationID uuid.UUID
	OwnerID    uuid.UUID
	Quantity   int64
}

type V2InventoryView struct {
	ItemID       uuid.UUID
	LotID        uuid.UUID
	LocationID   uuid.UUID
	OrderID      bool
	Quantity     int64
	ItemCode     string
	ItemName     string
	LotCode      string
	LocationCode string
	LocationKind string
}

type V2Item struct {
	ID     uuid.UUID
	Code   string
	Name   string
	Kind   string
	Unit   string
	Active bool
}

type V2Location struct {
	ID     uuid.UUID
	Code   string
	Name   string
	Kind   string
	Active bool
}

type V2Lot struct {
	ID     uuid.UUID
	ItemID uuid.UUID
	Code   string
	Active bool
}

type V2MaterialLedger struct {
	ID         int64
	DocumentID uuid.UUID
	ReversalID *uuid.UUID
	ItemID     uuid.UUID
	LotID      uuid.UUID
	LocationID uuid.UUID
	OwnerID    uuid.UUID
	Quantity   int64
	Movement   string
	RecordedAt time.Time
}

type V2MaterialLedgerView struct {
	ID         int64
	DocumentID uuid.UUID
	ReversalID *uuid.UUID
	ItemID     uuid.UUID
	LotID      uuid.UUID
	LocationID uuid.UUID
	OrderID    bool
	Quantity   int64
	Movement   string
	RecordedAt time.Time
}

type V2OutputBalance struct {
	SourceDocumentID uuid.UUID
	OutputLotID      uuid.UUID
	Bucket           string
	Quantity         int64
}

type V2OutputLedger struct {
	ID               int64
	DocumentID       uuid.UUID
	ReversalID       *uuid.UUID
	SourceDocumentID uuid.UUID
	OutputLotID      uuid.UUID
	Bucket           string
	Quantity         int64
	RecordedAt       time.Time
}

type V2OutputLot struct {
	ID                   uuid.UUID
	OrderID              uuid.UUID
	ProductionDocumentID uuid.UUID
	NewOutputQuantity    int64
}

type V2OutputLotView struct {
	ID                   uuid.UUID
	Code                 string
	OrderID              uuid.UUID
	ItemID               uuid.UUID
	ProductionDocumentID uuid.UUID
	NewOutputQuantity    int32
	PendingQuantity      int64
	AcceptedQuantity     int64
	RejectedQuantity     int64
	ReworkQuantity       int64
	DisposedQuantity     int64
	ReceivedQuantity     int64
}

type V2Reversal struct {
	ID         uuid.UUID
	DocumentID uuid.UUID
	Reason     string
	ActorID    uuid.UUID
	RecordedAt time.Time
}

type V2Session struct {
	TokenHash []byte
	UserID    uuid.UUID
	CsrfToken string
	CreatedAt time.Time
	ExpiresAt time.Time
	Revoked   bool
}

type V2User struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	Active       bool
	CreatedAt    time.Time
}

type V2UserRole struct {
	UserID uuid.UUID
	Role   string
}

type V2WorkOrder struct {
	ID                   uuid.UUID
	FinishedItemID       uuid.UUID
	TargetQuantity       int64
	StartAllowance       int64
	BomRevisionID        uuid.UUID
	InspectionRevisionID uuid.UUID
	AssignedUserID       uuid.UUID
	PlannedDate          string
	Status               string
	Version              int64
	BomSnapshot          []byte
	InspectionSnapshot   []byte
	CreatedBy            uuid.UUID
	CreatedAt            time.Time
}

type V2WorkOrderView struct {
	ID                   uuid.UUID
	FinishedItemID       uuid.UUID
	TargetQuantity       int64
	StartAllowance       int64
	BomRevisionID        uuid.UUID
	InspectionRevisionID uuid.UUID
	AssignedUserID       uuid.UUID
	PlannedDate          string
	Status               string
	Version              int64
	BomSnapshot          []byte
	InspectionSnapshot   []byte
	CreatedBy            uuid.UUID
	CreatedAt            time.Time
	NewOutputQuantity    int64
	PendingQuantity      int64
	AcceptedQuantity     int64
	RejectedQuantity     int64
	ReworkQuantity       int64
	DisposedQuantity     int64
	ReceivedQuantity     int64
	RemainingQuantity    int64
	FloorQuantity        int64
	ActiveSessions       int64
	HasVariances         bool
}

type V2WorkSession struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	UserID    uuid.UUID
	Status    string
	StartedAt time.Time
	EndedAt   pgtype.Timestamptz
}
