// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countItems = `-- name: CountItems :one
SELECT count(*) FROM items
WHERE ($1::text = '' OR kind = $1)
AND ($2::text = '' OR position(lower($2) IN lower(code || ' ' || name)) > 0)
`

type CountItemsParams struct {
	KindFilter string
	Search     string
}

func (q *Queries) CountItems(ctx context.Context, arg CountItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countItems, arg.KindFilter, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBOM = `-- name: CreateBOM :one
INSERT INTO boms (id, finished_item_id) VALUES ($1, $2) RETURNING id, finished_item_id, updated_at
`

type CreateBOMParams struct {
	ID             uuid.UUID
	FinishedItemID uuid.UUID
}

func (q *Queries) CreateBOM(ctx context.Context, arg CreateBOMParams) (Bom, error) {
	row := q.db.QueryRow(ctx, createBOM, arg.ID, arg.FinishedItemID)
	var i Bom
	err := row.Scan(&i.ID, &i.FinishedItemID, &i.UpdatedAt)
	return i, err
}

const createBOMLine = `-- name: CreateBOMLine :exec
INSERT INTO bom_lines (bom_id, component_item_id, quantity_per_unit) VALUES ($1, $2, $3)
`

type CreateBOMLineParams struct {
	BomID           uuid.UUID
	ComponentItemID uuid.UUID
	QuantityPerUnit int64
}

func (q *Queries) CreateBOMLine(ctx context.Context, arg CreateBOMLineParams) error {
	_, err := q.db.Exec(ctx, createBOMLine, arg.BomID, arg.ComponentItemID, arg.QuantityPerUnit)
	return err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (id, code, name, kind, unit) VALUES ($1, $2, $3, $4, $5) RETURNING id, code, name, kind, unit, created_at
`

type CreateItemParams struct {
	ID   uuid.UUID
	Code string
	Name string
	Kind string
	Unit string
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Kind,
		arg.Unit,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Kind,
		&i.Unit,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBOMLines = `-- name: DeleteBOMLines :exec
DELETE FROM bom_lines WHERE bom_id = $1
`

func (q *Queries) DeleteBOMLines(ctx context.Context, bomID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBOMLines, bomID)
	return err
}

const getBOM = `-- name: GetBOM :one
SELECT id, finished_item_id, updated_at FROM boms WHERE finished_item_id = $1
`

func (q *Queries) GetBOM(ctx context.Context, finishedItemID uuid.UUID) (Bom, error) {
	row := q.db.QueryRow(ctx, getBOM, finishedItemID)
	var i Bom
	err := row.Scan(&i.ID, &i.FinishedItemID, &i.UpdatedAt)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, code, name, kind, unit, created_at FROM items WHERE id = $1
`

func (q *Queries) GetItem(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Kind,
		&i.Unit,
		&i.CreatedAt,
	)
	return i, err
}

const listBOMLines = `-- name: ListBOMLines :many
SELECT i.id AS item_id, i.code, i.name, i.unit, l.quantity_per_unit
FROM bom_lines l JOIN items i ON i.id = l.component_item_id
WHERE l.bom_id = $1 ORDER BY i.id
`

type ListBOMLinesRow struct {
	ItemID          uuid.UUID
	Code            string
	Name            string
	Unit            string
	QuantityPerUnit int64
}

func (q *Queries) ListBOMLines(ctx context.Context, bomID uuid.UUID) ([]ListBOMLinesRow, error) {
	rows, err := q.db.Query(ctx, listBOMLines, bomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBOMLinesRow{}
	for rows.Next() {
		var i ListBOMLinesRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Code,
			&i.Name,
			&i.Unit,
			&i.QuantityPerUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, code, name, kind, unit, created_at FROM items
WHERE ($1::text = '' OR kind = $1)
AND ($2::text = '' OR position(lower($2) IN lower(code || ' ' || name)) > 0)
ORDER BY created_at DESC, id DESC LIMIT $4::bigint OFFSET $3::bigint
`

type ListItemsParams struct {
	KindFilter string
	Search     string
	RowOffset  int64
	RowLimit   int64
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems,
		arg.KindFilter,
		arg.Search,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Kind,
			&i.Unit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBOM = `-- name: LockBOM :one
SELECT id, finished_item_id, updated_at FROM boms WHERE finished_item_id = $1 FOR UPDATE
`

func (q *Queries) LockBOM(ctx context.Context, finishedItemID uuid.UUID) (Bom, error) {
	row := q.db.QueryRow(ctx, lockBOM, finishedItemID)
	var i Bom
	err := row.Scan(&i.ID, &i.FinishedItemID, &i.UpdatedAt)
	return i, err
}

const lockItem = `-- name: LockItem :one
SELECT id, code, name, kind, unit, created_at FROM items WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockItem(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, lockItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Kind,
		&i.Unit,
		&i.CreatedAt,
	)
	return i, err
}

const touchBOM = `-- name: TouchBOM :one
UPDATE boms SET updated_at = now() WHERE id = $1 RETURNING id, finished_item_id, updated_at
`

func (q *Queries) TouchBOM(ctx context.Context, id uuid.UUID) (Bom, error) {
	row := q.db.QueryRow(ctx, touchBOM, id)
	var i Bom
	err := row.Scan(&i.ID, &i.FinishedItemID, &i.UpdatedAt)
	return i, err
}
