// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countMovements = `-- name: CountMovements :one
SELECT count(*) FROM stock_movements
WHERE ($1::uuid IS NULL OR item_id = $1)
`

func (q *Queries) CountMovements(ctx context.Context, itemFilter *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMovements, itemFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBalance = `-- name: CreateBalance :exec
INSERT INTO inventory_balances (item_id) VALUES ($1)
`

func (q *Queries) CreateBalance(ctx context.Context, itemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createBalance, itemID)
	return err
}

const createMovement = `-- name: CreateMovement :exec
INSERT INTO stock_movements (id, item_id, delta, movement_type, receipt_id, result_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateMovementParams struct {
	ID           uuid.UUID
	ItemID       uuid.UUID
	Delta        int64
	MovementType string
	ReceiptID    *uuid.UUID
	ResultID     *uuid.UUID
}

func (q *Queries) CreateMovement(ctx context.Context, arg CreateMovementParams) error {
	_, err := q.db.Exec(ctx, createMovement,
		arg.ID,
		arg.ItemID,
		arg.Delta,
		arg.MovementType,
		arg.ReceiptID,
		arg.ResultID,
	)
	return err
}

const createReceipt = `-- name: CreateReceipt :one
INSERT INTO stock_receipts (id, item_id, quantity, note) VALUES ($1, $2, $3, $4) RETURNING id, item_id, quantity, note, created_at
`

type CreateReceiptParams struct {
	ID       uuid.UUID
	ItemID   uuid.UUID
	Quantity int64
	Note     string
}

func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) (StockReceipt, error) {
	row := q.db.QueryRow(ctx, createReceipt,
		arg.ID,
		arg.ItemID,
		arg.Quantity,
		arg.Note,
	)
	var i StockReceipt
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Quantity,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getBalance = `-- name: GetBalance :one
SELECT item_id, quantity, updated_at FROM inventory_balances WHERE item_id = $1
`

func (q *Queries) GetBalance(ctx context.Context, itemID uuid.UUID) (InventoryBalance, error) {
	row := q.db.QueryRow(ctx, getBalance, itemID)
	var i InventoryBalance
	err := row.Scan(&i.ItemID, &i.Quantity, &i.UpdatedAt)
	return i, err
}

const getReceipt = `-- name: GetReceipt :one
SELECT id, item_id, quantity, note, created_at FROM stock_receipts WHERE id = $1
`

func (q *Queries) GetReceipt(ctx context.Context, id uuid.UUID) (StockReceipt, error) {
	row := q.db.QueryRow(ctx, getReceipt, id)
	var i StockReceipt
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Quantity,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listInventory = `-- name: ListInventory :many
SELECT i.id AS item_id, i.code, i.name, i.kind, i.unit, b.quantity, b.updated_at
FROM items i JOIN inventory_balances b ON b.item_id = i.id
WHERE ($1::text = '' OR i.kind = $1)
AND ($2::text = '' OR position(lower($2) IN lower(i.code || ' ' || i.name)) > 0)
ORDER BY i.code ASC LIMIT $4::bigint OFFSET $3::bigint
`

type ListInventoryParams struct {
	KindFilter string
	Search     string
	RowOffset  int64
	RowLimit   int64
}

type ListInventoryRow struct {
	ItemID    uuid.UUID
	Code      string
	Name      string
	Kind      string
	Unit      string
	Quantity  int64
	UpdatedAt time.Time
}

func (q *Queries) ListInventory(ctx context.Context, arg ListInventoryParams) ([]ListInventoryRow, error) {
	rows, err := q.db.Query(ctx, listInventory,
		arg.KindFilter,
		arg.Search,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInventoryRow{}
	for rows.Next() {
		var i ListInventoryRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Code,
			&i.Name,
			&i.Kind,
			&i.Unit,
			&i.Quantity,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovements = `-- name: ListMovements :many
SELECT id, item_id, delta, movement_type, receipt_id, result_id, created_at FROM stock_movements
WHERE ($1::uuid IS NULL OR item_id = $1)
ORDER BY created_at DESC, id DESC LIMIT $3::bigint OFFSET $2::bigint
`

type ListMovementsParams struct {
	ItemFilter *uuid.UUID
	RowOffset  int64
	RowLimit   int64
}

func (q *Queries) ListMovements(ctx context.Context, arg ListMovementsParams) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, listMovements, arg.ItemFilter, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockMovement{}
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Delta,
			&i.MovementType,
			&i.ReceiptID,
			&i.ResultID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBalance = `-- name: LockBalance :one
SELECT item_id, quantity, updated_at FROM inventory_balances WHERE item_id = $1 FOR UPDATE
`

func (q *Queries) LockBalance(ctx context.Context, itemID uuid.UUID) (InventoryBalance, error) {
	row := q.db.QueryRow(ctx, lockBalance, itemID)
	var i InventoryBalance
	err := row.Scan(&i.ItemID, &i.Quantity, &i.UpdatedAt)
	return i, err
}

const setBalance = `-- name: SetBalance :exec
UPDATE inventory_balances SET quantity = $2, updated_at = now() WHERE item_id = $1
`

type SetBalanceParams struct {
	ItemID   uuid.UUID
	Quantity int64
}

func (q *Queries) SetBalance(ctx context.Context, arg SetBalanceParams) error {
	_, err := q.db.Exec(ctx, setBalance, arg.ItemID, arg.Quantity)
	return err
}
