// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Bom struct {
	ID             uuid.UUID
	FinishedItemID uuid.UUID
	UpdatedAt      time.Time
}

type BomLine struct {
	BomID           uuid.UUID
	ComponentItemID uuid.UUID
	QuantityPerUnit int64
}

type IdempotencyRequest struct {
	Operation   string
	Key         uuid.UUID
	RequestHash string
	ResourceID  uuid.UUID
	CreatedAt   time.Time
}

type InventoryBalance struct {
	ItemID    uuid.UUID
	Quantity  int64
	UpdatedAt time.Time
}

type Item struct {
	ID        uuid.UUID
	Code      string
	Name      string
	Kind      string
	Unit      string
	CreatedAt time.Time
}

type ProductionOrder struct {
	ID                uuid.UUID
	FinishedItemID    uuid.UUID
	PlannedQuantity   int64
	GoodQuantity      int64
	DefectiveQuantity int64
	CreatedAt         time.Time
}

type ProductionOrderMaterial struct {
	OrderID         uuid.UUID
	ComponentItemID uuid.UUID
	QuantityPerUnit int64
}

type ProductionResult struct {
	ID                uuid.UUID
	OrderID           uuid.UUID
	GoodQuantity      int64
	DefectiveQuantity int64
	Note              string
	CreatedAt         time.Time
}

type StockMovement struct {
	ID           uuid.UUID
	ItemID       uuid.UUID
	Delta        int64
	MovementType string
	ReceiptID    *uuid.UUID
	ResultID     *uuid.UUID
	CreatedAt    time.Time
}

type StockReceipt struct {
	ID        uuid.UUID
	ItemID    uuid.UUID
	Quantity  int64
	Note      string
	CreatedAt time.Time
}
