// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: production.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addOrderTotals = `-- name: AddOrderTotals :one
UPDATE production_orders SET good_quantity = good_quantity + $2, defective_quantity = defective_quantity + $3
WHERE id = $1 RETURNING id, finished_item_id, planned_quantity, good_quantity, defective_quantity, created_at
`

type AddOrderTotalsParams struct {
	ID                uuid.UUID
	GoodQuantity      int64
	DefectiveQuantity int64
}

func (q *Queries) AddOrderTotals(ctx context.Context, arg AddOrderTotalsParams) (ProductionOrder, error) {
	row := q.db.QueryRow(ctx, addOrderTotals, arg.ID, arg.GoodQuantity, arg.DefectiveQuantity)
	var i ProductionOrder
	err := row.Scan(
		&i.ID,
		&i.FinishedItemID,
		&i.PlannedQuantity,
		&i.GoodQuantity,
		&i.DefectiveQuantity,
		&i.CreatedAt,
	)
	return i, err
}

const claimRequest = `-- name: ClaimRequest :one
INSERT INTO idempotency_requests (operation, key, request_hash, resource_id) VALUES ($1, $2, $3, $4)
ON CONFLICT (operation, key) DO NOTHING RETURNING resource_id
`

type ClaimRequestParams struct {
	Operation   string
	Key         uuid.UUID
	RequestHash string
	ResourceID  uuid.UUID
}

func (q *Queries) ClaimRequest(ctx context.Context, arg ClaimRequestParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, claimRequest,
		arg.Operation,
		arg.Key,
		arg.RequestHash,
		arg.ResourceID,
	)
	var resource_id uuid.UUID
	err := row.Scan(&resource_id)
	return resource_id, err
}

const countOrders = `-- name: CountOrders :one
SELECT count(*) FROM production_orders
WHERE ($1::text = '' OR $1 =
  CASE WHEN good_quantity + defective_quantity = 0 THEN 'pending'
       WHEN good_quantity + defective_quantity = planned_quantity THEN 'completed' ELSE 'in_progress' END)
`

func (q *Queries) CountOrders(ctx context.Context, statusFilter string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders, statusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countResults = `-- name: CountResults :one
SELECT count(*) FROM production_results WHERE order_id = $1
`

func (q *Queries) CountResults(ctx context.Context, orderID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countResults, orderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO production_orders (id, finished_item_id, planned_quantity) VALUES ($1, $2, $3) RETURNING id, finished_item_id, planned_quantity, good_quantity, defective_quantity, created_at
`

type CreateOrderParams struct {
	ID              uuid.UUID
	FinishedItemID  uuid.UUID
	PlannedQuantity int64
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (ProductionOrder, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.ID, arg.FinishedItemID, arg.PlannedQuantity)
	var i ProductionOrder
	err := row.Scan(
		&i.ID,
		&i.FinishedItemID,
		&i.PlannedQuantity,
		&i.GoodQuantity,
		&i.DefectiveQuantity,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderMaterial = `-- name: CreateOrderMaterial :exec
INSERT INTO production_order_materials (order_id, component_item_id, quantity_per_unit) VALUES ($1, $2, $3)
`

type CreateOrderMaterialParams struct {
	OrderID         uuid.UUID
	ComponentItemID uuid.UUID
	QuantityPerUnit int64
}

func (q *Queries) CreateOrderMaterial(ctx context.Context, arg CreateOrderMaterialParams) error {
	_, err := q.db.Exec(ctx, createOrderMaterial, arg.OrderID, arg.ComponentItemID, arg.QuantityPerUnit)
	return err
}

const createResult = `-- name: CreateResult :one
INSERT INTO production_results (id, order_id, good_quantity, defective_quantity, note) VALUES ($1, $2, $3, $4, $5) RETURNING id, order_id, good_quantity, defective_quantity, note, created_at
`

type CreateResultParams struct {
	ID                uuid.UUID
	OrderID           uuid.UUID
	GoodQuantity      int64
	DefectiveQuantity int64
	Note              string
}

func (q *Queries) CreateResult(ctx context.Context, arg CreateResultParams) (ProductionResult, error) {
	row := q.db.QueryRow(ctx, createResult,
		arg.ID,
		arg.OrderID,
		arg.GoodQuantity,
		arg.DefectiveQuantity,
		arg.Note,
	)
	var i ProductionResult
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.GoodQuantity,
		&i.DefectiveQuantity,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, finished_item_id, planned_quantity, good_quantity, defective_quantity, created_at FROM production_orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (ProductionOrder, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i ProductionOrder
	err := row.Scan(
		&i.ID,
		&i.FinishedItemID,
		&i.PlannedQuantity,
		&i.GoodQuantity,
		&i.DefectiveQuantity,
		&i.CreatedAt,
	)
	return i, err
}

const getRequest = `-- name: GetRequest :one
SELECT operation, key, request_hash, resource_id, created_at FROM idempotency_requests WHERE operation = $1 AND key = $2
`

type GetRequestParams struct {
	Operation string
	Key       uuid.UUID
}

func (q *Queries) GetRequest(ctx context.Context, arg GetRequestParams) (IdempotencyRequest, error) {
	row := q.db.QueryRow(ctx, getRequest, arg.Operation, arg.Key)
	var i IdempotencyRequest
	err := row.Scan(
		&i.Operation,
		&i.Key,
		&i.RequestHash,
		&i.ResourceID,
		&i.CreatedAt,
	)
	return i, err
}

const getResult = `-- name: GetResult :one
SELECT id, order_id, good_quantity, defective_quantity, note, created_at FROM production_results WHERE id = $1
`

func (q *Queries) GetResult(ctx context.Context, id uuid.UUID) (ProductionResult, error) {
	row := q.db.QueryRow(ctx, getResult, id)
	var i ProductionResult
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.GoodQuantity,
		&i.DefectiveQuantity,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listOrderMaterials = `-- name: ListOrderMaterials :many
SELECT i.id AS item_id, i.code, i.name, i.unit, m.quantity_per_unit
FROM production_order_materials m JOIN items i ON i.id = m.component_item_id
WHERE m.order_id = $1 ORDER BY i.id
`

type ListOrderMaterialsRow struct {
	ItemID          uuid.UUID
	Code            string
	Name            string
	Unit            string
	QuantityPerUnit int64
}

func (q *Queries) ListOrderMaterials(ctx context.Context, orderID uuid.UUID) ([]ListOrderMaterialsRow, error) {
	rows, err := q.db.Query(ctx, listOrderMaterials, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderMaterialsRow{}
	for rows.Next() {
		var i ListOrderMaterialsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Code,
			&i.Name,
			&i.Unit,
			&i.QuantityPerUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, finished_item_id, planned_quantity, good_quantity, defective_quantity, created_at FROM production_orders
WHERE ($1::text = '' OR $1 =
  CASE WHEN good_quantity + defective_quantity = 0 THEN 'pending'
       WHEN good_quantity + defective_quantity = planned_quantity THEN 'completed' ELSE 'in_progress' END)
ORDER BY created_at DESC, id DESC LIMIT $3::bigint OFFSET $2::bigint
`

type ListOrdersParams struct {
	StatusFilter string
	RowOffset    int64
	RowLimit     int64
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]ProductionOrder, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.StatusFilter, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductionOrder{}
	for rows.Next() {
		var i ProductionOrder
		if err := rows.Scan(
			&i.ID,
			&i.FinishedItemID,
			&i.PlannedQuantity,
			&i.GoodQuantity,
			&i.DefectiveQuantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResults = `-- name: ListResults :many
SELECT id, order_id, good_quantity, defective_quantity, note, created_at FROM production_results WHERE order_id = $1
ORDER BY created_at DESC, id DESC LIMIT $3::bigint OFFSET $2::bigint
`

type ListResultsParams struct {
	OrderID   uuid.UUID
	RowOffset int64
	RowLimit  int64
}

func (q *Queries) ListResults(ctx context.Context, arg ListResultsParams) ([]ProductionResult, error) {
	rows, err := q.db.Query(ctx, listResults, arg.OrderID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductionResult{}
	for rows.Next() {
		var i ProductionResult
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.GoodQuantity,
			&i.DefectiveQuantity,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrder = `-- name: LockOrder :one
SELECT id, finished_item_id, planned_quantity, good_quantity, defective_quantity, created_at FROM production_orders WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockOrder(ctx context.Context, id uuid.UUID) (ProductionOrder, error) {
	row := q.db.QueryRow(ctx, lockOrder, id)
	var i ProductionOrder
	err := row.Scan(
		&i.ID,
		&i.FinishedItemID,
		&i.PlannedQuantity,
		&i.GoodQuantity,
		&i.DefectiveQuantity,
		&i.CreatedAt,
	)
	return i, err
}
